# Generated by Django 5.0.6 on 2024-06-02 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomTipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='ISBN', unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comida', to='myapp.tipocomida')),
            ],
        ),
    ]
