# Generated by Django 5.0.6 on 2024-06-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='ISBN'),
        ),
    ]
